export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export const GET_ONE_USER = "GET_ONE_USER";
export const GET_ONE_USER_SUCCESS = "GET_ONE_USER_SUCCESS";
export const GET_ONE_USER_FAILURE = "GET_ONE_USER_FAILURE";

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE";

export const GET_POSTS = "GET_POSTS"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE"

export const GET_POSTS_BY_ID = "GET_POSTS_BY_ID"

export const ADD_POST = "ADD_POST"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILURE = "ADD_POST_FAILURE"

export const EDIT_POST = "EDIT_POST"
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE"

export const GET_ONE_POST = "GET_ONE_POST"
export const GET_ONE_POST_SUCCESS = "GET_ONE_POST_SUCCESS"
export const GET_ONE_POST_FAILURE = "GET_ONE_POST_FAILURE"

export const DELETE_ONE_POST = "DELETE_ONE_POST"
export const DELETE_ONE_POST_SUCCESS = "DELETE_ONE_POST_SUCCESS"
export const DELETE_ONE_POST_FAILURE = "DELETE_ONE_POST_FAILURE"

export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE"

export const ADD_COMMENT = "ADD_COMMENT"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE"

export const EDIT_COMMENT = "EDIT_COMMENT"
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"
export const EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE"

export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"

export const GET_POST_BY_TYPE = "GET_POST_BY_TYPE"
export const GET_POST_BY_TYPE_SUCCESS = "GET_POST_BY_TYPE_SUCCESS"
export const GET_POST_BY_TYPE_FAILURE = "GET_POST_BY_TYPE_FAILURE"

// export const SEND_MESSAGE = "SEND_MESSAGE"
// export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
// export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE"

export const GET_SEARCHED_INPUT_NAME = "GET_SEARCHED_INPUT_NAME";
export const GET_SEARCHED_INPUT_USER_TYPE = "GET_SEARCHED_INPUT_USER_TYPE";

export const ADD_LIKE = "ADD_LIKE";
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const ADD_LIKE_FAILURE = "ADD_LIKE_FAILURE";

export const REMOVE_LIKE = "REMOVE_LIKE";
export const REMOVE_LIKE_SUCCESS = "REMOVE_LIKE_SUCCESS";
export const REMOVE_LIKE_FAILURE = "REMOVE_LIKE_FAILURE";

export const GET_LIKES = "GET_LIKES";
export const GET_LIKES_SUCCESS = "GET_LIKES_SUCCESS";
export const GET_LIKES_FAILURE = "GET_LIKES_FAILURE";

export const CHECK_ABILITE_TO_LIKE = "CHECK_ABILITE_TO_LIKE";
export const CHECK_ABILITE_TO_LIKE_SUCCESS = "CHECK_ABILITE_TO_LIKE_SUCCESS";
export const CHECK_ABILITE_TO_LIKE_FAILLURE = "CHECK_ABILITE_TO_LIKE_FAILLURE";